import { DeviceTier, ModelInfo } from '../types';

export const RECOMMENDED_MODELS: ModelInfo[] = [
  {
    id: 'smollm-135m',
    name: 'SmolLM 135M Instruct',
    repoId: 'HuggingFaceTB/SmolLM2-135M-Instruct-GGUF',
    fileName: 'smollm2-135m-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct-GGUF/resolve/main/smollm2-135m-instruct-q4_k_m.gguf',
    sizeMB: 100,
    quantization: 'Q4_K_M',
    params: '135M',
    tier: DeviceTier.ULTRA_LOW,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'smollm-360m',
    name: 'SmolLM 360M Instruct',
    repoId: 'HuggingFaceTB/SmolLM2-360M-Instruct-GGUF',
    fileName: 'smollm2-360m-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/main/smollm2-360m-instruct-q4_k_m.gguf',
    sizeMB: 250,
    quantization: 'Q4_K_M',
    params: '360M',
    tier: DeviceTier.ULTRA_LOW,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'qwen-0.5b',
    name: 'Qwen 2.5 0.5B Instruct',
    repoId: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF',
    fileName: 'qwen2.5-0.5b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf',
    sizeMB: 400,
    quantization: 'Q4_K_M',
    params: '0.5B',
    tier: DeviceTier.LOW,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'smollm-1.7b',
    name: 'SmolLM 1.7B Instruct',
    repoId: 'HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF',
    fileName: 'smollm2-1.7b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q4_k_m.gguf',
    sizeMB: 1000,
    quantization: 'Q4_K_M',
    params: '1.7B',
    tier: DeviceTier.LOW,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'phi-3-mini',
    name: 'Phi-3 Mini 4K Instruct',
    repoId: 'microsoft/Phi-3-mini-4k-instruct-gguf',
    fileName: 'Phi-3-mini-4k-instruct-q4.gguf',
    downloadUrl: 'https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf',
    sizeMB: 2200,
    quantization: 'Q4_0',
    params: '3.8B',
    tier: DeviceTier.MEDIUM,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'gemma-2-2b',
    name: 'Gemma 2 2B Instruct',
    repoId: 'google/gemma-2-2b-it-GGUF',
    fileName: 'gemma-2-2b-it-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/google/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf',
    sizeMB: 1500,
    quantization: 'Q4_K_M',
    params: '2B',
    tier: DeviceTier.MEDIUM,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'llama-3.2-3b',
    name: 'Llama 3.2 3B Instruct',
    repoId: 'hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF',
    fileName: 'llama-3.2-3b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/hugging-quants/Llama-3.2-3B-Instruct-Q4_K_M-GGUF/resolve/main/llama-3.2-3b-instruct-q4_k_m.gguf',
    sizeMB: 2000,
    quantization: 'Q4_K_M',
    params: '3B',
    tier: DeviceTier.HIGH,
    downloadStatus: 'not_downloaded',
  },
  {
    id: 'mistral-7b',
    name: 'Mistral 7B Instruct v0.3',
    repoId: 'MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF',
    fileName: 'Mistral-7B-Instruct-v0.3.Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3.Q4_K_M.gguf',
    sizeMB: 4400,
    quantization: 'Q4_K_M',
    params: '7B',
    tier: DeviceTier.PREMIUM,
    downloadStatus: 'not_downloaded',
  },
];

export const getModelsForTier = (tier: DeviceTier): ModelInfo[] => {
  const tierOrder = [
    DeviceTier.ULTRA_LOW,
    DeviceTier.LOW,
    DeviceTier.MEDIUM,
    DeviceTier.HIGH,
    DeviceTier.PREMIUM,
  ];
  const tierIndex = tierOrder.indexOf(tier);
  return RECOMMENDED_MODELS.filter(
    (model) => tierOrder.indexOf(model.tier) <= tierIndex
  );
};
